/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package number;

import java.io.IOException;

import number.data.DataManager;

public class App {

    public static void main(String[] args) {
        try {
            DataManager.downloadData("result.json");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
